name: Timer
main: com.josephbleau.bukkit.timer.TimerPlugin
version: 1.0
description: Create, remove, and manager timers kept by the server.
commands:
  timer:
    description: Control and monitor timers.
    usage: /timer [add|clear|start|stop|list|show] <player> <time string>